library(stringi)
library(data.table)
library(openxlsx)
library(httr)
library(readxl)
library(janitor)
library(dplyr)
library(gdata)
library(lubridate)


setwd("/home/shannon/NAPS/spec_shan/NAPSdata")
# don't need to create header dictionaries - just read the data directly into a 
# list of lists 

# vector of columns names that should be characters 
# (generated by looking at all possible col names)
# also all flags 
charCol <- c("sample_type", "sampling_type", "c_f", "cart", "cartridge", "media", 
             "f_c", "fraction") 
#--------------------------------------------------------------------------------  
# Now read files into lists
#--------------------------------------------------------------------------------

## Function: getHeader
# Find which row contains the headers 
## -----------------------------------------------------
## Inputs: file:  file to be read
## Output: i, the row which contains the header
## Process: Looks for a row that contains "NAPS" or "Date", returns the index of
##          that row
getHeader <- function(file){
  i <- 0L
  found_header <- FALSE
  while(found_header == FALSE){
    i <- i+1
    if(any(grep(paste0( c("NAPS", "Date") , sep = "", collapse = "|"), file[i,], 
                ignore.case = TRUE, value = FALSE))){
      found_header <- TRUE
    }
  }
  i
}


## Function: removeEmptyRows
## -----------------------------------------------------
## Inputs: file:  data frame to be cleaned
## Output: dt_frm, the cleaned data frame
## Process: Removes rows that is all NA (except the date)
removeEmptyRowsCols <- function(dt_frm){
  dt_frm[!all(is.na(dt_frm[,2:ncol(dt_frm)])), ] #colSums(is.na(dt_frm))<nrow(dt_frm)]
  
  #df[rowSums(is.na(df))<ncol(df),colSums(is.na(df))<nrow(df)]
}

# Removes rows that has more the n blank values 
delete_na_rows <- function(df, n) {
  df[rowSums(is.na(df)) <= n,]
}

## Function: removeEmptyRows
## -----------------------------------------------------
## Inputs: dt_frm:  data frame with all character columns
## Output: dt_frm, with cols converted to numeric 
## Process: Converts columns to numeric 
##          Which cols? All that aren't in the charCol vector and does not
##          contain date, flag or naps 
getNumericalCols <- function(dt_frm){
  cols <- names(dt_frm)[! names(dt_frm) %in% charCol]
  grep(paste0( c("NAPS", "Date", "flag", "time", "x0", "id", "na") , sep = "", collapse = "|"), cols, 
       ignore.case = TRUE, value = TRUE, invert = TRUE)
}


## Function: getFile
## -----------------------------------------------------
## Inputs: file_path: path of file to be read
##         sheet: sheet of file to be read 
## Output: a data frame with the appropriate column names 
##          for 2011+ NAPS data
getFile <- function(file_path, sheet){
  # Read in the file 
  tmp <- suppressMessages(read_excel(file_path, sheet = sheet, col_names = FALSE,
                          na = c("NA","", " ", "-", "-999","-999.000"), trim_ws = TRUE))

  i <- getHeader(tmp)
  
  #get cartridges - used for column naming
  cart <- sub("N/A|Cartridge", NA, as.character(as.vector(tmp[2,])) , ignore.case = TRUE)
  idx_cart <- which(!is.na(cart))
  
  df <- removeEmptyRowsCols(tmp[i+1:nrow(tmp),])
  names(df) <-  tmp[i,] 
  df_col <- getNumericalCols(df %>%  clean_names())

  df <- df  %>% 
    clean_names()  %>%
    mutate(date = as.Date(as.numeric(sampling_date), origin =  "1899-12-30"), 
           year = year(date), month = month(date), day = day(date)) %>%
    mutate_at(df_col,as.numeric)  %>%
    select(-c(contains("TIME"), "sampling_date", contains("naps"))) %>%
    relocate(all_of(c("date", "year", "month", "day")), after = 1) 
  
  delete_na_rows(df[rowSums(is.na(df))<ncol(df),colSums(is.na(df))<nrow(df)],4) # remove na
}


## Function: getFile_xls
## -----------------------------------------------------
## Inputs: file_path: path of file to be read
## Output: a data frame with the appropriate column names 
##          for 2003-2010 NAPS xls data
##          read_excel() has issues reading .xls 
getFile_xls <- function(file_path){
  tmp <- read.xls(file_path, na.strings = c("NA","", " ", "-", "-999","-999.000"))
  i <- getHeader(tmp)
  

  df <- (tmp[i+1:nrow(tmp),])
  names(df) <-  tmp[i,]
  df <- removeEmptyRowsCols(df)
  
  df_col <- getNumericalCols( df %>%  clean_names())
  
  df <- df %>% 
    clean_names() %>%
    mutate(date = as.Date(date)) %>%
    mutate(year = year(date), month = month(date), day = day(date)) %>%
    mutate_at(df_col,as.numeric)  %>%
    select(-c(contains("TIME"), contains("naps"))) %>%
    relocate(all_of(c("date", "year", "month", "day")), after = 1)
  
  delete_na_rows(df[rowSums(is.na(df))<ncol(df),colSums(is.na(df))<nrow(df)], 4)  # remove na

}

## Function: readData
## -----------------------------------------------------
## Input: dir - a directory of xlsx files to read
## Output: a list of lists containing the dir contents 
##         List is arranged as Station -> Sheet name -> Data 
readData <- function(dir){
  FilesSheets <- getFilesandSheets(dir)
  
  # generate the header data frame
  station <- unlist(lapply(strsplit(FilesSheets$files, "_"), "[[", 3)) 
  header <- vector("list", length(unique(station)))
  names(header) <- unique(station)
  
  for(s in unique(station)){
    header[[s]] <- vector("list", length = length(FilesSheets$sheetnames))
    names(header[[s]]) <- FilesSheets$sheetnames
  }
  
  for(i in 1:length(FilesSheets$files)){
    stn <- station[i]
    for(t in FilesSheets$sheetnames[FilesSheets$sheetnames %in% excel_sheets(FilesSheets$files[i])]){
      tmp <- getFile(FilesSheets$files[i], t)
       if(length(header[[stn]][[t]]) == 0){
         header[[stn]][[t]] <- tmp
       }else {
        header[[stn]][[t]] <- merge(header[[stn]][[t]], tmp, all.x = TRUE, all.y = TRUE,
                             by = intersect(names(header[[stn]][[t]]), names(tmp)))
      }
      print(sprintf("Read %s, sheet %s",FilesSheets$files[i], t))
    }
  }
  
  header
}

## Function: readData_pmpart
## -----------------------------------------------------
## Input: dir - a directory of xls files to read
## Output: a list of lists containing the dir contents 
##         List is arranged as Station -> Data 
## -----------------------------------------------------
readData_pmpart <- function(dir){
  files <- list.files(path = paste0(getwd(), "/", dir), full.names = TRUE)
  station <- unlist(lapply(strsplit(files, "_|\\."), "[[", 3)) 
  
  header <- vector("list", length(unique(station)))
  names(header) <- unique(station)
  
  for(i in 1:length(files)){
    tmp <- getFile_xls(files[i])
    if(length(header[[station[i]]]) == 0){
      header[[station[i]]] <- tmp
    }else {
      header[[station[i]]] <- merge(header[[station[i]]], tmp, all.x = TRUE, all.y = TRUE,
                           by = intersect(names(header[[station[i]]]), names(tmp)))

    }
    print(sprintf("Read %s, %f precent read",files[i], round((i/length(files))*100,2)))
  }

  header
}



## Function: readData_spec
## -----------------------------------------------------
## Input: dir - a directory of xls files to read
## Output: a list of lists containing the dir contents 
##         List is arranged as Station -> File type -> Data 
## -----------------------------------------------------
readData_spec <- function(dir){

  # generate the header data frame
  files <- list.files(path = paste0(getwd(), "/", dir), full.names = TRUE)
  file_type <- unlist(lapply(strsplit(files, "_|\\."), "[[", 4)) 
  station <- unlist(lapply(strsplit(files, "_|\\."), "[[", 3)) 
  
  header <- vector("list", length(unique(station)))
  names(header) <- unique(station)
  
  for(s in unique(station)){
    header[[s]] <- vector("list", length = length(unique(file_type)))
    names(header[[s]]) <- unique(file_type)
  }
  
  for(i in 1:length(files)){
    tmp <- getFile_xls(files[i])
    if(length(header[[station[i]]][[file_type[i]]]) == 0){
      header[[station[i]]][[file_type[i]]] <- tmp
    }else {
      header[[station[i]]][[file_type[i]]] <- merge(header[[station[i]]][[file_type[i]]], tmp, all.x = TRUE, all.y = TRUE,
                                      by = intersect(names(header[[station[i]]][[file_type[i]]]), names(tmp)))
    }
    print(sprintf("Read %s, %s, %s",files[i], station[i], file_type[i]))
  }

  header
}


## Function: getFilesandSheets
## -----------------------------------------------------
## Input: d - the directory of interest
## Output: a list of the excel files within the directory and its relevant sheets
getFilesandSheets <- function(d){
  files <- list.files(path = paste0(getwd(), "/", d), full.names = TRUE)
  
  # Don't want to read metadata, changelogs or station info 
  sheetnames <- grep('metadata|change|csv|station', unique(unlist(lapply(files, function(i){excel_sheets(i)}))) , 
                     ignore.case = TRUE, invert = TRUE, value = TRUE)
  
  list("files" = files, "sheetnames" = sheetnames)
}




## Function: listToExcel
## -----------------------------------------------------
## Generate excel file from the list argument 
## Input: outputPath: path of excel file
##        myList: List of data, each item corresponds to a sheet 
## Output: an excel file containing the data from myList
listToExcel <- function(outputPath, myList){
  if (class(myList) != "list") stop("Second argument to function must be a list")
  if (length(myList) < 1) stop("Second argument must have at least one element")
  if (class(myList[[1]]) != "data.frame") stop("Second argument to function must be a list of data frames")
  
  wb <- createWorkbook()
  mapply(function(i){addWorksheet(wb, paste0(i))}, names(myList))
  mapply(function(i){ writeData(wb, wb$sheet_names[i], names(myList[[i]]), startRow = 1, startCol = 1)}, 1:length(myList))
  saveWorkbook(wb, file = outputPath, overwrite = TRUE)
}




## -----------------------------------------------------
## -----------------------------------------------------
## Generate the lists for each directory/file type 
## -----------------------------------------------------
## -----------------------------------------------------
#listToExcel("SPEC_Header.xlsx", spec)
#listToExcel("PM25_Header.xlsx", pm25dat)
#listToExcel("PM10_Header.xlsx", pm10dat)


## Read the files
## -----------------------------------------------------
pm10dat <- readData("IntegratedPM2.5-10")
pm25dat <- readData("IntegratedPM2.5")
spec <- readData_spec("PMSPECIATION") 
pmpart <- readData_pmpart("PMPART25")


spec <- lapply(spec, function(x){Filter(Negate(is.null), x)})
pmpart <- lapply(pmpart, function(x){Filter(Negate(is.null), x)})
pm10dat <- lapply(pm10dat, function(x){Filter(Negate(is.null), x)})
pm25dat <- lapply(pm25dat, function(x){Filter(Negate(is.null), x)})


save(file = "spec_read.rda", spec)
save(file = "pmpart_read.rda", pmpart)
save(file = "pm10_read.rda", pm10dat)
save(file = "pm25_read.rda", pm25dat)









